### ISSUE TITLE
توضیحات بیشتر

### ISSUE THREAD

**Issue by aliqasemzadeh** [parsisolution/gateway#1]
سلام
وقت بخیر

در مورد این بسته و اینکه اضافه کردن درگاه های جدید خیلی ساده هست توضیحات بیشتری ارائه کنید.

مثلا 
[Mabna gateway manual 2.0.1.6.pdf](https://github.com/parsisolution/gateway/files/2611408/Mabna.gateway.manual.2.0.1.6.pdf)

یا درگاه موبایلی SEP
را بخواهید اضافه کنید

[SEP-PPG-Purchase With Mobile Number-TechnicalSpecification.pdf](https://github.com/parsisolution/gateway/files/2611411/SEP-PPG-Purchase.With.Mobile.Number-TechnicalSpecification.pdf)

در مورد واحد های پولی هم توضیحات بدهید ممنون.

**Comment by hamed-ehtesham** [comment]
سلام آقای قاسم زاده
وقت شما هم بخیر

من مبنای کارم رو
laravel socialite
قرار دادم و از اون ایده گرفتم و البته قبلش
poolport
و پروژه ی نسبتا متروک
larabook
و همینطور پروژه ی شما رو که ادامه ی
larabook
بود رو دیده بودم اول قصد داشتم فقط دو تا درگاه اضافه کنم به پروژه ی شما و تموم بشه ولی وقتی رفتم توی کد که این کار رو انجام بدم دیدم اصلا قابل قبول نیست کدهای
duplicate
کلاس های
tightly coupled
و ... البته من از شما قدردانی میکنم که پروژه ی
larabook
رو ادامه دادید اما مشکل اینجاست که کد از همون اول که
poolport
هست زیاد خوب نبوده حتی از نظر نام گذاری و منطق و همینطور که پیش رفته بعضی جاها بدتر شده
مثل همین قابلیت جدید
description
که یک نفر اضافه کرده به پروژه ی
larabook
البته انصافا خیلی جاهای خوب داره کد و کد من هم تا حد زیادی شبیه به
poolport
شده اما بعضی جاها هم آدم متعجب میشه مثل این که به بقیه اش نمیخوره
در هر صورت هدف این بود که کسی که میخواد درگاه جدید به پروژه اضافه کنه مجبور نباشه یک کلاس دیگه رو بره نگاه کنه چطور کار میکنه و بفهمه کلاس پدر چطور کار میکنه و یه مقدار کد رو هم صرفا
copy/paste
کنه به خاطر همون مساله ی
duplicate
که گفتم و یک مورد دیگه هم کدهای
larabook
رو وقتی باز میکنید کدها پر از خطا هست و من فکر میکنم به خاطر این باشه که کد رو توی یک پروژه ی
laravel
توسعه دادن و بعد به صورت یک
package
در اوردن یا این که خطاها براشون مهم نبوده صرفا همین که کار میکنه بس بوده که فکر میکنم این مورد هم توی نوشتن تست افراد رو دچار مشکل کنه که توی
issue
های اون هم یک همچین موردی دیدم

**Comment by hamed-ehtesham** [comment]
سادگی استفاده از این
package
مخصوصا زمانی دیده میشه که بخواهید از یک
ide
مثل
phpstorm
استفاده کنید اونوقت هست که تماما بهتون پیشنهاد داده میشه چطور باید با این پروژه کار کنید
وقتی بخواید کد رو برای یک درگاه جدید بنویسید باید چند تا
method
رو پیاده سازی کنید که هم ورودی و هم خروجی مشخصی داره اسم ها هم معقول و با نگاه کردن به پروژه ی
braintree
که برای
paypal
هست انتخاب شده اونوقت هست که نه باید به کد بقیه ی درگاه ها نگاه کنید نه این که بخواید مستقیم با 
DB
طرف بشید بخواید مستقیم
try/catch
بنویسید و زمانی هم که به عنوان کاربر بخواهید کار کنید منظورم زمانی هست که نخواهید درگاهی اضافه کنید باز هم به خاطر انتخاب کردن
type
های درست میدونید که هر جا چه چیزهایی برای ورودی نیاز دارید و چه جواب هایی به شما برگردانده شده
در مورد پول هم جاهای مربوط یعنی هم در توضیحات سازنده ی کلاس
Amount
و هم در تابع های مربوطه
setCurrency, getCurrency
امده است که واحد ها حروف سه حرفی هستند که پیشنهاد میشه مطابق با این لینک باشند چون احتمالا من این درگاه رو در آینده اضافه کنم
https://developers.braintreepayments.com/reference/general/currencies
اما چون واحد پولی کشور خودمون که درگاه های فعلی هم همه روی اون هستند در اینجا تعریف نشده من خودم دو واحد جدید ریال رو با
IRR
و تومان رو با
IRT
تعریف کردم و تومان هم به صورت پیشفرض هست اگه واحد انتخاب نشه و همینطور این کلاس این دو واحد رو هم به هم تبدیل میکنه یعنی اگر شما واحد رو تومان قرار بدید در پایگاه داده هم با تومان ذخیره میشه ولو این که درگاه تون با ریال کار کنه یا برعکس
البته همین دو واحد به هم تبدیل میشه و مثلا اگه از
USD
استفاده کنید خطا میده که درگاه به واحد های پول ایران نیاز داره
من قصد داشتم برای تمامی درگاه هایی که نمونه کدش توی سیستم
poolport
یا سیستم شما وجود داره تبدیل شده اش به درگاه این سیستم رو اضافه کنم اما چند درگاه که فکر میکنم منسوخ شده بودند و سایت نداشتند مثل
jahanpay
و چند درگاه هم کدشون رو که نگاه میکردم به نظر نمیرسید کد درست عمل کنه به خاطر همین میخواستم مطمئن باشم که کد درستی هست
مثل همین درگاه موبایلی سامان که شما توی پروژه ی خودتون زحمت ش رو کشیدید من مطمئن نبودم که خودتون استفاده میکنید و کار میکنه یا صرفا از روی مستندات ساختید
و فکر میکنم درگاه
paypal
رو هم شما زحمتش رو کشیده باشید البته من منبع کد رو توی
paypal
دیدم به خاطر این اضافه نکردم که وقت نداشتم برم دنبال
error
هایی که
paypal
برمیگردونه بگردم شما صرفا
return false
میکردید اگه درست خاطرم باشه
بسیار خوشحال میشم از این به بعد درگاه های این پروژه رو توسعه بدید
در ضمن برای توسعه ی درگاه های این پروژه نیازی نیست که در این پروژه تغییری ایجاد بشه میشه از کلاس درگاه رو در پروژه ی خودتون ایجاد کنید و ازش استفاده کنید حتی میتونید با استفاده از کدی مثل این
```php
Gateway::extend('paypal', function () {
    return new Paypal(app(), config('gateways.paypal'));
});
```
درگاه خودتون رو به مجموعه ی درگاه ها اضافه کنید استفاده از این کد تفاوتش با این که هر بار
new Paypal
بزنید این هست که با استفاده از این کد و سپس گرفتن کلاس
Paypal
توسط
Gateway::of('paypal')
شما همیشه یک کلاس رو دریافت میکنید و چند بار کلاس درگاه ساخته نمیشه که سربار رو کم میکنه
البته این که گفتم نیاز نیست درگاه به این پروژه اضافه بشه منظور بسته بودن این پروژه نیست و از درگاه های جدید استقبال میشه

**Comment by aliqasemzadeh** [comment]
سلام
بابت زحمتی که شما کشیدید ازتون قدر دانی می کنم
من در پکیج خودم بیشتر تلاش کردم پیکیج قبلی را یکم اصلاح کنم و قابل استفاده کنم و یک مقداری هم روند کارش جالب نبود این را هم قبول دارم ولی فرصت از نو نوشتن را هم نداشتم.

من خودم به شدت استقبال می کنم که یک پکیج خوب ساخته شود بخصوص اگر شما
Maintenance
بهتری برای این پکیج داشته باشید و اسمی که برای سازمان انتخاب کردید خیلی قشنگه
ParsiSolution


من از پیکجتون استفاده می کنم ولی به نظرم باید مستندات قوی تر ارائه شود بیشترین مشکل ما در حوزه مستندات هست مثلا چطور یک درگاه جدید را اضافه کنیم.

روشی که نوشتید کاملا صحیح هست و من کد ها را بررسی کردم به نظر می آید خوبه هستند

من درگاه موبایلی را تا حدودی پیشرفتم ولی بخاطر مشغله ای که داشتم دیگر ادامه ندادم اگر شما فرصت دارید مبنا 2 و دماوند، درگاه موبایلی سامان را به پکیج خودتون اضافه کنید و البته یک پی هم که درگاه ارزی دارد عالیه می تونم بگم این طوری دیگه واقعا راهکار پارسی کامل خواهد بود.



شما همه درگاه ها را تست کردید؟
اگر تست کردید و پس از تست خودم من می تونم پکیچ خودم را طوری تنظیم کنم که به صورت پیشنهاد این پکیج را معرفی کند

**Comment by hamed-ehtesham** [comment]
خیلی ممنون از حرف های قشنگتون

حتما
maintenance
بهتر از
larabook
خواهد بود

در مورد مستندات هم درست میفرمایید در اولین فرصت یک سایت مخصوص مستندات درست میکنم که توضیح بده هم روش کار کردن رو هم روش افزودن درگاه جدید رو اما با توجه به برنامه ی کاریم فکر میکنم تقریبا یک ماه آینده باشه این اتفاق

در مورد این درگاه های جدید اضافه کردن درگاه ارزی بسیار جذاب به نظر میرسه
من همین الان رفتم یک پی ثبت نام کردم و نمونه کدشون رو دیدم
در اولین فرصت به سیستم اضافه اش میکنم

من چند سالی هست پروژه ای زیر دستم نبوده که نیاز به درگاه داشته باشه اما الان چند پروژه دارم که به درگاه نیاز دارند برای همین این پروژه روز به روز بهتر میشه مثلا احتمالا همین امروز ساختار
db
تغییر کنه و این که هنوز چون پروژه ها تکمیل نشده هنوز از هیچ بانکی اقدام به گرفتن درگاه نکردند مشتری هامون اما این مورد هم توی همین یکی دو ماه اتفاق میافته البته نمیدونم مایل باشند چه درگاهی بگیرند ولی تفاوتی نمیکنه هر کدوم رو بگیرند باعث میشه
maintenance
این پروژه روی اون درگاه بهتر بشه

من 5 درگاه واسطی که هست رو 4 تاش رو تست کردم و
pay.ir
رو هم دو هفته است ثبت نام کردم ولی هنوز بررسی نکردند و پاسخی ندادند و گفتند تیکت هم نزنید در این رابطه
در مورد درگاه های بانک هم که گفتم به زودی چند درگاه رو مشتری هامون میگیرن و تست میشه
ولی این کدها از روی کدهای
poolport
و کدهای شما اومده البته
poolport
ادعا میکنه که درگاه هاش رو تست کرده اما باز هم نمیشه مطمئن بود
در مورد اون سه درگاهی که فرمودید هم اضافه کردن "صرفا" از روی مستندات بدون تست واقعی رو زیاد نمیشه بهش اطمینان کرد به خاطر همین اگه کسی این درگاه ها رو داشته باشه بهتره و من هم اگه مشتری هامون این درگاه ها رو بگیرند حتما اضافه شون میکنم

**Comment by aliqasemzadeh** [comment]
سلام
من همه درگاه های بانکی را دارم 
نصب می کنم تست می کنم

شما اون سه درگاه را اضافه کنید تست کنیم اوکی باشه خیلی سریع پکیج رشد می کند.

اگر مایلید باهم روی راهکار پارسی کار کنیم

**Comment by aliqasemzadeh** [comment]
می تونیم کارهای فارسی شده
یا خاص ایرانی را اضافه کنیم


متاسفانه دامنه پارسی سلوشن را گرفتن مگر نه یک وبلاگ می توانست خیلی کارآیی داشته باشه

**Comment by hamed-ehtesham** [comment]
تلگرام یا توییتر میتونیم صحبت کنیم؟
@H4M3D3

**Comment by AGhasemzadeh** [comment]
09177886099
واتسآپ
