### ISSUE TITLE
تکمیل شدن پکیج

### ISSUE THREAD

**Issue by aliqasemzadeh** [parsisolution/gateway#13]
سلام 

بیایید یک کاری کنید
اسم جدول gateway transaction 
را بکنیم 
transactions
یک فیلد 
user_id
هم اضافه بشه

جدول واحد ها هم اضافه کنیم 
بعد یک trait 
هم برای کاربر بزنیم که موحودی کار بر را بده
یک درگاه فیک هم میگذارم به اسم پرداخت دستی
عملا تمام کارهای مال سیستم لاراول را میشه باهاش انجام داده

**Comment by hamed-ehtesham** [comment]
اسم جدول که جزو موارد قابل تنظیم هست هر کسی میتونه برای خودش تغییر بده
جدول
transactions
معمولا به تراکنش های داخلی برنامه مربوط میشه که معمولا یک جوری مثلا 1-1 یا
1-n
به جدول تراکنش های درگاه متصل میشه
من از پیشنهادات شما بسیار متشکرم اما پیداست که شما سیستم رو یک بعدی تصور میکنید فقط برای حالتی که کاربر میخواد تمام کارهاش رو با این
package
انجام بده و هیچ چیزی رو درون سیستم خودش برای ارتباط با درگاه کنترل نکنه در صورتی که نباید یک حالت خاص استفاده از
package
رو مشکل کلی بدونیم و
package
رو طوری تغییر بدیم که فقط اون مشکل خاص رو حل کنه
