### ISSUE TITLE
کاربرد دقیق $gateway->stateless();

### ISSUE THREAD

**Issue by aliqasemzadeh** [parsisolution/gateway#14]
سلام
وقت بخیر
کاربرد دقیق 
````
$gateway->stateless();
````
چیه؟

**Comment by hamed-ehtesham** [comment]
سلام
وقت شما هم بخیر
state
در واقع همون
session
هست. در حالت عادی اطلاعات که مهمترین شون که در همه ی درگاه ها وجود داره یعنی شماره ی تراکنش (و البته هر درگاه میتونه اطلاعات دیگه ای هم بنا به نیاز به این شماره اضافه کنه) توسط
session
بین درخواست قبل از رفتن به درگاه و بعد از برگشت از درگاه جا به جا میشن همینطور یک
token
هم ایجاد میشه که غیر از
csrf
هست چون
csrf
رو حداقل خود کاربر داره اگه کس دیگه ای از کاربر اون رو به دست نیاورده باشه و زمان برگشت از درگاه اولین چیزی که بررسی میشه یکسان بودن این
token
ایجاد شده با
token
موجود در درخواست از سمت درگاه هست که خودمون به درگاه میدیم زمان قرار دادن
callback_url
که یک لایه ی امنیتی ایجاد میکنه
و اگه یکسان نبود طبیعی هست که خطا برمیگردونه
اما در حالت
stateless
اولا تمامی اطلاعات از جمله شماره تراکنش توسط
callback_url
قرار داده میشه که در این حالت طبیعتا باید لایه ی امنیتی هم توسط خود فرد استفاده کننده از
package
ایجاد بشه

**Comment by aliqasemzadeh** [comment]
کدام حالت امنیتی بیشتری دارد؟
بهتره است از کدام یکی استفاده کنیم؟

**Comment by hamed-ehtesham** [comment]
عرض کردم حالت
`stateless`
امنیتی ندارد و باید لایه یا لایه های امنیتی توسط خود فرد ایجاد شود
حالت `پیش فرض` یک لایه ی امنیتی ایجاد میکند

**Comment by hamed-ehtesham** [comment]
poolport
و
larabook
لایه ی امنیتی ندارند

**Comment by aliqasemzadeh** [comment]
من 
`$gateway->stateless();`
را برداشتم
الان خطا می دهد 
The request parameters are in valid.

**Comment by hamed-ehtesham** [comment]
حالت
stateless
یا
stateful
باید در قبل از فرستادن به درگاه و بعد از برگشتن از آن یکسان باشد
این خطا را برای این دریافت میکنید که قبل از فرستادن به درگاه
stateful
یا حالت `پیش فرض` را انتخاب کرده اید
اما برای
settlement
در زمان
callback
دارید به تابع
settle
مقدار
`true`
را میفرستید که باعث میشود
stateless
شود و در واقع درون درخواست دنبال شماره تراکنش بگردد و ان را پیدا نکند زیرا درون
session
ذخیره شده است

**Comment by aliqasemzadeh** [comment]
سلام
میشه یک نمونه خودتون بگید تا مثل همان عمل کنیم.

**Comment by hamed-ehtesham** [comment]
قبل از فرستادن کاربر به درگاه در زمان ایجاد درگاه از

```php
$gateway->stateless();
```

استفاده نکنید و در زمان برگشت
به تابع هایی که مقدار
stateless
رو میگیرند چیزی نفرستید
یعنی توابع
`settle`, `fromSettleRequest`, `transactionFromSettleRequest`
مقدار پیش فرض همه درست تنظیم شده است

**Comment by aliqasemzadeh** [comment]
````
            try {
                $gateway = Gateway::of($request->gateway);
                $gateway->callbackUrl(url('invoice/callback', ['id'=>$request->invoice_id]));
                $transaction = new RequestTransaction(new Amount($invoice->total,'IRR'));
                $authorizedTransaction = $gateway->authorize($transaction);
                return $gateway->redirect($authorizedTransaction);
            } catch (Exception $e) {
                flash($e->getMessage())->error();
            }

````

callback

````
                $settledTransaction = Gateway::settle(true);
                $transaction = new Transaction();
                $transaction->gateway_transaction_id = $settledTransaction->getId();
                $transaction->invoice_id = $invoice->id;
                $transaction->account_id = config('gateway.'.session('gateway').'.account-id');
                $transaction->user_id = Auth::user()->id;
                $transaction->category_id = config('platform.sale-category-id');
                $transaction->amount = MoneyUtil::database($invoice->total);
                $transaction->name = Auth::user()->name;
                $transaction->email = Auth::user()->email;
                $transaction->mobile = Auth::user()->mobile;
                $transaction->description = "پرداخت فاکتور شماره:" . $invoice->id;
                $transaction->save();
                $invoice->paid_at = date("Y-m-d H:i:s");
                $invoice->status = 'paid';
                $invoice->save();
````

**Comment by hamed-ehtesham** [comment]
callback
```php
$settledTransaction = Gateway::settle();
```

**Comment by vahidalvandi** [comment]
برای کسی که تازه میخواد باهاش کار کنه گنگه !
یه جور مستندات دقیق تهیه کنید چون خیلی ازکاربران با سیستم های درگاه سرکار دارند و میتونه موجب  پیشرفتش بشه

**Comment by hamed-ehtesham** [comment]
حتما مستندات در اولین فرصت خالی که پیدا کنم اضافه میکنم ولی توی همین
issue
ها سوال جواب ها خیلی از قسمت ها توضیح داده شده
