### ISSUE TITLE
 $settledTransaction چه محتوای با خود دارد؟

### ISSUE THREAD

**Issue by aliqasemzadeh** [parsisolution/gateway#15]
سلام
 $settledTransaction
چه محتوای با خود دارد
مثلا آیا شماره تراکنش داخل بانک اطلاعاتی خودمان را دارد که بتوانیم با کمک آن تراکنش خودمان را به آن وصل کنیم.

**Comment by hamed-ehtesham** [comment]
با سلام

![image](https://user-images.githubusercontent.com/14082075/49688029-775ee380-fb21-11e8-8fdc-de8fbe36bb53.png)

بله شماره تراکنش با
```php
$settledTransaction->getId()
```

به دست میاد
