### ISSUE TITLE
paid_at درسته

### ISSUE THREAD

**Issue by aliqasemzadeh** [parsisolution/gateway#16]
https://github.com/parsisolution/gateway/blob/7f301780d44754304140eb7f7df5954310ff75e7/migrations/2018_11_14_193213_create_gateway_transactions_table.php#L35

paid_at درسته

**Comment by hamed-ehtesham** [comment]
با تشکر از دقت نظر شما
`payed`
یک شکل خاص بود که برای معنای دریانوردی به کار میرفت به خاطر همین غلط املایی رو نشون نداده بود
