### ISSUE TITLE
واحد پول درگاه ها

### ISSUE THREAD

**Issue by aliqasemzadeh** [parsisolution/gateway#17]
سلام
به نظرم باید واحد پول درگاه ها وجود داشته باشه
چون الان واقعا گیج کننده است نمیشه راحت و سریع از درگاه استفاده کرد

**Comment by hamed-ehtesham** [comment]
سلام
لطفا بیشتر توضیح بدید
برای چه کسی گیج کننده است و چرا؟

از دید کاربر یا کسی که میخواهد درگاه اضافه کند؟

**Comment by aliqasemzadeh** [comment]
سلام
الان من توی صبا پی باید قیمت ها را به تومن به اون سمت بفرستم و در بانک اطلاعاتی خودم همگی ریال هست
عددی که داره ارسال میشه کاملا اشتباه هست

**Comment by hamed-ehtesham** [comment]
خب دارید اشتباه استفاده میکنید حتما
احتمالا توی قسمت اول مشکل دارید زمانی که میخواهید درگاه رو ایجاد کنید و قیمت رو وارد میکنید
وقتی یک کلاس
Amount
ایجاد میکنید حالت اصلی روی تومان است
اگر میخواهید با ریال کار کنید و در پایگاه داده هم قیمت ها به ریال ذخیره شود باید زمانی که کلاس
Amount
رو ایجاد میکنید صریحا بگویید که واحد به ریال است به این شکل

```php
$transaction = new RequestTransaction(new Amount(120000, 'IRR')); // 120000 Riyal
```

**Comment by aliqasemzadeh** [comment]
دقیقا کد من برای صبا پی به صورت زیر هست
````
$transaction = new RequestTransaction(new Amount($invoice->total,'IRR'));
```
ولی عدد دریافتی اشتباه است

**Comment by hamed-ehtesham** [comment]
مطمئن هستید صبا با تومان کار میکنه؟
تبدیل واحد مشکلی نداره من دوباره همین الان با زرین پال تست کردم زرین پال هم با تومان کار میکنه تبدیل از ریال به درستی انجام شد

**Comment by aliqasemzadeh** [comment]
سلام
بله
فقط یک سوال الان داره می گه
API KEY اشتباه درحالی که درسته و پرداخت را درست انجام می دهد.

**Comment by hamed-ehtesham** [comment]
توسط شماره #18 درست شد
