### ISSUE TITLE
واحد پول $settledTransaction->getAmount(); چیست؟

### ISSUE THREAD

**Issue by aliqasemzadeh** [parsisolution/gateway#19]
سلام
وقت بخیر
واحد پول 
$settledTransaction->getAmount(); 
چیست؟

**Comment by hamed-ehtesham** [comment]
سلام
وقت شما هم بخیر
همان واحدی که در پایگاه داده ذخیره شده
در نتیجه همان واحدی که زمان فرستادن استفاده کردید
