### ISSUE TITLE
سخت بودن توسعه

### ISSUE THREAD

**Issue by aliqasemzadeh** [parsisolution/gateway#2]
سلام
وقت بخیر
امروز برای یکی از دوستان می خواستم درگاه واسط بزنم خیلی سخت بود فکر کنم یکم باید بیشتر توضیحات بدهید

اسم توابع را تغییر بدهید

مثلا

startPay

verifyPay

settlePay

checkPay

این طور اسم هایی باشد

حالا این که چرا این طوری اسم گذاشتید باید خودتون توضیح بدهید.

**Comment by hamed-ehtesham** [comment]
سلام
وقت بخیر
اسم های کجا رو میفرمایید از دید کاربر یا از دید کسی که میخواد درگاه به سیستم اضافه کنه؟

اسم ها با توجه به [این](https://articles.braintreepayments.com/get-started/transaction-lifecycle) انتخاب شده

با این که مرحله ی
verify
از
settle
جدا بشه موافق هستم اما برای بیشتر درگاه ها این مرحله یکی هست به خاطر همین جدا نکردم که در کد هم پیچیدگی زائد وارد نشه

منظورتون رو از
checkPay
متوجه نمیشم که قراره چه نقشی به عهده بگیره

**Comment by aliqasemzadeh** [comment]
check یک جورایی همان verify 
هست

حتما نیاز به مستندات هست

**Comment by hamed-ehtesham** [comment]
من یک توضیح مختصر میدم تا انشاءالله در اولین فرصت مستندات رو هم آماده کنم:
چند مرحله رو هر تراکنش طی میکنه در مرحله ی اول یک
RequestTransaction
ایجاد میکنیم که یک جزء اصلی داره که مبلغ هست و یک جزء اختیاری که
extra
نام داره و معمولا برای بیشتر درگاه ها شامل
description
میشه ولی اگه اطلاعات بیشتری هم نیاز باشه مثل درگاه زرین پال که میتونیم براش شماره یا ایمیل مشتری رو هم بفرستیم توسط همین فرستاده میشه و در پایگاه داده هم ذخیره میشه که توی نمونه کد صفحه ی اول هم مثالش اومده به این شکل

```php
    $transaction = new RequestTransaction(new Amount(12000)); // 12000 Toman
    $transaction->setExtra([
        'mobile' => '9122628796', // mobile of payer (for zarinpal)
        'email'  => 'ali@gmail.com', // email of payer (for zarinpal)
    ]);
    $transaction->setExtraField('description', 'توضیحات من');
```

بعد این
requestTransaction
ساخته شده رو میدیم به تابع
authorize
تا این تابع به ما یک
authorizedTransaction
برگردونه که شامل شماره ارجاع بانک که معمولا درگاه ها بهش 
refId
میگن هست و همینطور
id
تراکنش در پایگاه داده ی خودمون
و همینطور این
authorizedTransaction
رو میفرستیم به
redirect
به خاطر این که درگاه به
refId
نیاز داره معمولا
و بعد از این که از بانک برمیگردیم هم 2 تا تابع وجود داره از دید کسی که میخواد درگاه اضافه کنه
اولی
validateSettlementRequest
هست که بررسی میکنه درخواستی که برای
settlement
به ما فرستاده شده دارای فیلد های لازم برای اون درگاه هست یا خیر
کار خیلی ساده ای انجام میده و در اینجا با درگاه ارتباط نمیگیریم صرفا
input
های
request
رو بررسی میکنیم
شبیه به کاری که در بیشتر
controller
ها در برنامه انجام میشه به صورت دقیق تر ابتدای توابع
store و update
در جاهایی که
resource
داریم
بنابرین
validate
اسم خوبی هست
و اگر درخواست مون تمامی ورودی های لازم رو نداشت
 throw error
میکنیم در غیر این صورت (ورودی های لازم رو داشت) به تابع
settleTransaction
میریم که اینجا بعضی درگاه ها صرفا
verify
رو انجام میدن که البته این خودش به معنای 
settle
هست چون اگه
verify
تا یه زمانی که برای هر درگاه متفاوت هست انجام نشه تراکنش رو برگشت میزنن
بعضی هم مثل ملت هم
verify
میکنن هم بعدش جدا
settle
میکنن که ما هر دو رو در همین قسمت قرار میدیم

**Comment by aliqasemzadeh** [comment]
برای 
callback
اگر یک بار بنویسیم کفایت می کند؟
یا اینکه نه؟

**Comment by hamed-ehtesham** [comment]
متوجه سوال نشدم
چی رو یک بار بنویسیم؟

**Comment by aliqasemzadeh** [comment]
توی پکیج قبلی ما بدون درنظر گرفتن درگاه یک کال بک می نویشتیم و از آن استفاده می کردیم
الان این سیستم چطوری هست؟

**Comment by hamed-ehtesham** [comment]
فکر کنم نمونه کد صفحه اول رو ملاحظه نکردید
اگر منظورتون از دید کاربر هست نه کسی که میخواد درگاه جدید اضافه کنه احتمالا جواب سوال این هست

```php
try {

    $settledTransaction = Gateway::settle(true); // true argument for stateless
    $trackingCode = $settledTransaction->getTrackingCode();
    $refId = $settledTransaction->getReferenceId();
    $cardNumber = $settledTransaction->getCardNumber();

    // تراکنش با موفقیت سمت بانک تایید گردید
    // در این مرحله عملیات خرید کاربر را تکمیل میکنیم

} catch (\Parsisolution\Gateway\Exceptions\RetryException $e) {

    // تراکنش قبلا سمت بانک تاییده شده است و
    // کاربر احتمالا صفحه را مجددا رفرش کرده است
    // لذا تنها فاکتور خرید قبل را مجدد به کاربر نمایش میدهیم

    echo $e->getMessage() . "<br>";

} catch (\Exception $e) {

    // نمایش خطای بانک
    echo $e->getMessage();
}
```

و اگر منظورتون از دیدگاه فردی هست که میخواهد درگاه اضافه کند
از 

```php
$this->getCallback($transaction)
```

استفاده میشه

**Comment by aliqasemzadeh** [comment]
خب یک نکته دیگر

ما در نرم افزار می خواهیم هر فرد درگاه خودش را داشته باشد
حالا 
callback 
به چه صورت میشه؟

**Comment by hamed-ehtesham** [comment]
خب سه تا راه حل به ذهنم میرسه که اولی بهتره اولی این هست که میتونید کاربر رو به عنوان پارامتر ورودی از داخل آدرس به دست بیارید (یعنی همون اول که میخواهید ادرس
callback
رو قرار بدید یک
unique token
هم قرار بدید که سمت
callback
ازش فرد به دست بیاد
دومین راه که البته این هم راه خوبی هست این هست که همون زمانی که تراکنش رو ایجاد کردید و به تابع
authorize
فرستادید و یک
authorizedTransaction
به دست اوردید که درونش 
id
تراکنش قرار داره در پایگاه داده این تراکنش رو به فرد منتسب کنید تا بعدا در
callback
با گرفتن تراکنش
settledTransaction
بتونید کاربر رو ازش به دست بیارید این در نمونه کد نیست اما
ide
بهتون میگه که
settledTransaction
شامل
id, refId
هم میشه همونطور که توی 
authorizedTransaction
به دست میاد و راه آخر که از دو راه قبلی بدتر هست اما باز هم یک راه هست اینه که نه
callback
ها ادرس های متفاوتی داشته باشن و نه این که پایگاه داده رو طوری ایجاد کنید که فرد رو منتسب به تراکنش کنه و اون این هست که طبق توضحات چند
comment
قبل میتونید 
id
فرد رو توسط
extra
جابجا کنید مثلا به این شکل

```php
    $transaction = new RequestTransaction(new Amount(12000)); // 12000 Toman
    $transaction->setExtraField('personID', $personID);
```

و این در پایگاه داده ذخیره میشه

**Comment by hamed-ehtesham** [comment]
در راه حل آخر سمت
callback
به این شکل میتوانید به
personID
دسترسی داشته باشید

```php
    $personID = $settledTransaction->getExtraField('personID');
```

**Comment by aliqasemzadeh** [comment]
اتفاقا به نظرم راه آخر راه خوبیه 
چون توی سیستم های دیگری هم این روش را داشتند ولی یک مشکل وجود دارد
` $settledTransaction = Gateway::settle(true);`
کجا باید 
config
را بهش بدهیم.

ببینید هر فرد برای خودش درگاه می گیره و فقط ما بهشون نرم افزار می دهیم.

**Comment by aliqasemzadeh** [comment]
اما مشکل اینجاست که چطوری باید 
config
که مربوط به مشتری هست را 
load
کرد

**Comment by hamed-ehtesham** [comment]
البته من باز هم پیشنهادم راه حل اول یا دوم هست

ولی برای مشکل مربوط به
config
های جداگانه من یک نسخه ی جدید (1.1.0) گذاشتم بعد از
update
به این شکل میتونید استفاده کنید

```php
$transaction = Gateway::transactionFromSettleRequest(true);

switch (strtoupper($transaction->provider))
{
    case GatewayManager::ZARINPAL:
        $driver = new Zarinpal(app(), [
            'merchant-id'  => 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx',
            'server'       => 'test',
        ]);
        break;
}
$driver->setTransactionId($transaction->id);

$settledTransaction = $driver->settle();
```

**Comment by hamed-ehtesham** [comment]
راستی این
`true`
هایی که فرستاده میشه برای حالت
`stateless`
هست که `حالت پیش فرض` **نیست**

**Comment by aliqasemzadeh** [comment]
درسته
این طوری شاید بشه مشکل را رفع کرد

**Comment by hamed-ehtesham** [comment]
باز هم اگه مشکلی بود بفرمایید با هم حلش کنیم
