### ISSUE TITLE
چرا در زمان بازگشت دوتا select داریم

### ISSUE THREAD

**Issue by aliqasemzadeh** [parsisolution/gateway#22]
select * from `gateway_transactions` where `id` = '154478886484' limit 1
370μs
/vendor/parsisolution/gateway/src/GatewayManager.php:155
db
select * from `gateway_transactions` where `id` = '154478886484' limit 1
210μs
/vendor/parsisolution/gateway/src/Transaction.php:155
db

در زمان بازگشت از دیتابیس بازم دوتا کوئری هست.
فاجعه هست.

**Comment by hamed-ehtesham** [comment]
210μs == فاجعه؟

اصلاح میشه

**Comment by aliqasemzadeh** [comment]
وقتی تعداد زیاد بشه بله
فاجعه هست

فقط یک سوال شما خودتون این درگاه ها را تست کردید/؟

**Comment by hamed-ehtesham** [comment]
من خودم 4 درگاه
جیبیت - پردانو - زرین پال و نکست پی رو تست و استفاده میکنم

**Comment by aliqasemzadeh** [comment]
اینا ها همه واسط هستند اصلا اعتباری ندارند

باید درگاه های رسمی تست بشوند.

**Comment by hamed-ehtesham** [comment]
اگه اینقدر تعداد براتون مهم هست باید فکری برای مشکل قبلی بکنیم که 3 تا بود اون 3 در عمل در تعدادی که شما در موردش صحبت میکنید میتونه به خیلی بیشتر از 3 مثلا 4 5 6 بیانجامه البته من خودم دلیلش رو نمیدونستم چرا همچین چیزی در نظر گرفته بودن و
auto increment
استفاده نکرده بودن اما چون درگاه برای تست نداشتم تغییر ندادم وگرنه استفاده از
auto increment
تعداد رو به 2 کاهش میده که اون رو هم میشه حتی 1 کرد اگه شما وظیفه ی تست ش رو بر عهده بگیرید انجام بدیم خیلی خوب میشه

**Comment by hamed-ehtesham** [comment]
من درگاه های رسمی رو هنوز ندارم در واقع پروژه هایی که این مجموعه رو براشون نوشتم هنوز هیچ کدوم به مرحله ی عملیاتی نرسیده که براشون درگاه بگیرن ولی به زودی اون اتفاق هم میافته

**Comment by aliqasemzadeh** [comment]
الان این بسته تست نشده هست

بیشترین حساسیت روی بانک های اصلی هست نه روی واسط ها چون واسط های خودشون کد های آماده زیاد دارند

شما ویرایش کنید من تست می کنم
من همه درگاه را دارم

**Comment by hamed-ehtesham** [comment]
پس من به زودی تعداد
query
هم رفت هم برگشت رو به یک کاهش میدم شما زحمت تست ش رو بکشید ممنون

**Comment by hamed-ehtesham** [comment]
سلام برای `رفت` من اول به یک کاهش دادم تعداد رو بعد دیدم بیشتر درگاه ها مخصوصا
psp
ها به
`id`
از سمت ما نیاز دارن معمولا تحت عنوان
`orderId` یا `invoiceNo` یا `paymentId` یا `CRN`
به کار رفته
 به خاطر همین یکی بهش اضافه کردم و الان برای رفت همیشه روی 2 هست
برای `برگشت` هم من
`select`
ها رو حساب کرده بودم گفته بودم به یک کاهش میدم در حالی که یک
`update`
برای
`status`
و یک
`insert`
برای
log
هم وجود داشت یعنی در مجموع 3 تا که اونها رو هم با یک واحد کاهش به 2 رسوندم

برای نصب از

```shell
composer require parsisolution/gateway dev-dev
```

استفاده کنید تا وقتی که تست بشه روی اینجا توسعه رو انجام میدیم
