### ISSUE TITLE
دلیل کار نکردن لایه امنیتی

### ISSUE THREAD

**Issue by aliqasemzadeh** [parsisolution/gateway#25]
سلام
?_token=jUBYPawk0OAM1UMX8AmfF1dPRzw6c03SJvLoDkn8&amp;transaction_id=154479258229
آدرس باید 
&amp;
را به 
&
تبدیل کنید اگر این کار را کنیم احتمال بسیار زیاد لایه امنیتی درست کار می کند
که اون وقت حسابی خوب میشه

**Comment by hamed-ehtesham** [comment]
سلام
مورد اول این که زمانی که لایه ی امنیتی فعال هست
transaction_id
درون آدرس برگشت نیست
آدرسی که شما فرستادید لایه ی امنیتی در آن فعال نیست

مورد دوم این که متوجه منظور شما نشدم تبدیل & به & یعنی چه؟ مگر هر دو یکی نیستند؟

**Comment by aliqasemzadeh** [comment]
& amp;
با 
&
یکی نیست.

مثلا لایه امنیتی دار بزنید.

**Comment by hamed-ehtesham** [comment]
تفاوت رو الان متوجه شدم اما
بعضی از درگاه ها مثل صبا پی زمانی که میخوان
callback
رو تعیین کنن برای درگاه

```php
urlencode($this->getCallback($transaction)),
```

از همچین کدی استفاده میکنن احتمالا این مشکل رو حل کنه چون اون
amp;
رو ما جایی اضافه نمیکنیم احتمالا سمت درگاه اتفاق میافته

**Comment by aliqasemzadeh** [comment]
سلام
بله دقیقا
این را برای همه درگاه ها لطفا اضافه کنید
احتمال زیاد مشکل مبنا هم رفع شود

من فکر کردم به صورت داخلی این کار انجام می شود.

**Comment by hamed-ehtesham** [comment]
میترسم اونهایی که این براشون
set
نشده به مشکل بخورند در اون حالت

**Comment by aliqasemzadeh** [comment]
نه مشکلی بر نمی خوریم
تست کنید اتفاقا درست کار می کنند
من خودم قبلا این کار را کردم ولی داخلی نبود توی برنامه خودم بود

**Comment by hamed-ehtesham** [comment]
من تست کردم
جیبیت و زرین پال (و شاید درگاه های دیگه) مشکل دارن باهاش کاملا

نظرتون چی هست که به عنوان یک پارامتر ورودی قرار بدم به شکل زیر؟

```php
$this->getCallback($transaction, true)
```

**Comment by aliqasemzadeh** [comment]
این فکر خوبیه.

**Comment by hamed-ehtesham** [comment]
مبنا رو هم تغییر دادم امیدوارم مشکلش حل شده باشه

**Comment by aliqasemzadeh** [comment]
سلام
بد تر شد
http%3A%2F%2Fsrssms.ir%2Fpayment%2Fcallback%2F1%3F_token%3DxGtbczsVUOyfJvoUc9YS5bdqnlMKQdyosUvAZe6B%26transaction_id%3D154484203463

آدرس آمد به نظر می آید همون که قبلا بوده است درست بوده.

**Comment by hamed-ehtesham** [comment]
سلام
بله
پس مبنا هم جزو همون هاست که مشکل داره
نمیدونم شما چطور گفتید که همه رو اینطوری کنیم

من مشکل
`amp;`
رو پیدا و حل کردم امیدوارم اینبار درست شده باشه

**Comment by aliqasemzadeh** [comment]
سلام
من حدث زدم مال این باشه
چون هنوز با ساختار پکیج شما خو نگرفتم
امروز عصر تست می کنم

**Comment by aliqasemzadeh** [comment]
من توی یک پروژه saas
دارم از بسته شما استفاده می کنم اگر بهینه و خوب باشه و همه
psp 

ها اضافه بشود عالیه

**Comment by hamed-ehtesham** [comment]
بله از اونجا که گفتید تعداد تراکنش هاتون به شدت بالاست متوجه شدم
مشکلی نیست من هم میخوام به حالت
optimize
شده برسیم با هم
