### ISSUE TITLE
log_at is correct

### ISSUE THREAD

**Issue by aliqasemzadeh** [parsisolution/gateway#26]
https://github.com/parsisolution/gateway/blob/7ae8c5cbb8b2882b222fe21cbfc3588d4c982f47/migrations/2018_11_14_193229_create_gateway_status_log_table.php#L33

log_at is correct
@hamed-ehtesham

**Comment by hamed-ehtesham** [comment]
سلام
توسعه روی
[`dev`](https://github.com/parsisolution/gateway/tree/dev)
انجام میشود

برای نصب از

```shell
composer require parsisolution/gateway dev-dev
```

استفاده کنید
