### ISSUE TITLE
چرا پاسارگاد حذف شده

### ISSUE THREAD

**Issue by vahidalvandi** [parsisolution/gateway#27]
؟؟

**Comment by hamed-ehtesham** [comment]
سلام و وقت بخیر
اینطور که یادم هست کدش به نظر درست نمیومد اگر شما درگاه ش رو دارید با کمک هم اضافه کنیم

**Comment by vahidalvandi** [comment]
من در حال حاضر از سرویس larabook استفاده کرده ام و الان یکی از پروژه هام روی پاسارگاد است . یکمم کدش پیچیده است اما درسته . تا من ساختار پروژه شما را متوجه بشم کمی طول میشکه اگر شما فرصت داشته باشید و روش کار کنید خیلی خوب است .

ممنون

**Comment by hamed-ehtesham** [comment]
شما میتونید داخل
laravel app
خودتون درگاه به این سیستم اضافه کنید لازم نیست این
package
تغییری بکنه بنابرین من کلاس ش رو مینویسم در اولین فرصت به شما میدم که داخل برنامه خودتون تست کنید اگر جواب گرفتید به این مجموعه اضافه کنم

خوبه؟

**Comment by vahidalvandi** [comment]
ok

**Comment by hamed-ehtesham** [comment]
سلام این چیزی هست که من از تبدیل بهش رسیدم اما قسمت های نه چندان خوبی توش هست من تا جایی که میشد درست ش کردم اما معلوم نیست خطاها چی هستند و کد خطا کجا تولید میشه که درست نیست فایل
certificate.xml
که کنارش قرار گرفته معلوم نیست برا چی هست احتمالا یک نمونه ی زائد باشه
[Pasargad.zip](https://github.com/parsisolution/gateway/files/2707503/Pasargad.zip)
فایل
[pasargad-redirector.blade.zip](https://github.com/parsisolution/gateway/files/2707509/pasargad-redirector.blade.zip)
هم در جای مناسب قرار بدید

**Comment by hamed-ehtesham** [comment]
و اما آموزش اضافه کردن
اولین کار این هست که نوع جدید رو به پایگاه داده اضافه کنید در فایل
migration
یا به صورت دستی هر طور راحت هستید مثلا در
`database/migrations/2018_11_14_193213_create_gateway_transactions_table.php`
این خط رو تغییر بدید به این شکل
```php
$table->enum('provider', array_merge(\Parsisolution\Gateway\GatewayManager::availableDrivers(), ['PASARGAD']));
```
و بعد یک
controller
شبیه به این باید کار کنه
[MainController.zip](https://github.com/parsisolution/gateway/files/2707548/MainController.zip)

**Comment by vahidalvandi** [comment]
در مورد 
certificate.xml
درگاه پاسارگاد تنها درگاهی است که به جای 
ip base
بودن از یک فایل برای آپلود در روت سایت استفاده میکنه.
این فایل هم همیشه ثابت نیست و هرکسی درگاه بگیره بانک بهش این فایل را میده

----------

افزودن یک مقدار 
enum 
به دیتابیس هم میشه دستی انجام داد ؟
-----------

**Comment by vahidalvandi** [comment]
کد نمونه را دیدم . به نظرم بهتره تکمیل ترش کنید تا در نسخه جدید اضافه باشد . 
در کل من سیستم شما را امروز بررسی کردم و رضایت بخش بود مخصوصا واحد پولی و ویژگی های اضافه ای که روی هر پرداخت ثبت میشه . 

تشکر

**Comment by hamed-ehtesham** [comment]
بله متوجه این امر بودم و این که گفتم یک نمونه ی زائد هست بیشتر منظورم از نظر مکانی بود نه خود فایل خود فایل که به صورت حتم باید تغییر کنه
اما به نظر حتی برای نمونه هم خوب نیست چون جای مناسبی قرار نداره

با
database tools
ها یا 
command
احتمالا ممکن باشه
https://stackoverflow.com/questions/1501958/how-do-i-add-more-members-to-my-enum-type-column-in-mysql

**Comment by hamed-ehtesham** [comment]
منظورتون از تکمیل تر چی هست؟
این که گفتم خطا منظورم این نبود که کدی که بهتون دادم خطا داره
منظورم خطاهایی که برای تراکنش ها اتفاق میافته بود

من چون درگاه پاسارگاد رو ندارم فعلا نمیتونم کد رو بهتر کنم چیزی که براتون فرستادم بهترین چیزی بود که میشد از تبدیل کدهای موجود به دست اورد

خواهش میکنم

**Comment by aliqasemzadeh** [comment]
سلام
یعنی پاسارگاد را حذف کردید

لطفا اضافه کنید حتی اگر کلاس های خالی باشد.

پروژه را ناقص نکنید لطفا

**Comment by hamed-ehtesham** [comment]
سلام آقای قاسم زاده
ببخشید من چند روز مسافرت بودم و احتمالا چند روز آینده هم همین منوال مسافرت رو داشته باشم و دیر جواب بدم
در پیام های اخیر نحوه ی اضافه کردنش وجود داره کلاسش رو تبدیل کردم
هر زمانی که فردی تست بکنه و بگه کار میکنه اضافه میکنیم به نسخه اصلی نه این که کلاس خالی بذاریم

**Comment by aliqasemzadeh** [comment]
سلام
شما اضافه کنید من تست می کنم.

**Comment by hamed-ehtesham** [comment]
عرض کردم در همین صفحه هم کد ها هست هم نحوه ی اضافه کردن

**Comment by hamed-ehtesham** [comment]
تست کردید بفرمایید اضافه کنیم مثل بقیه ی درگاه ها

**Comment by khanzadimahdi** [comment]
use https://github.com/shetabit/payment

**Comment by hamed-ehtesham** [comment]
با سلام
درگاه‌های بسیار زیادی از جمله پاسارگاد به نسخه‌ی ۲ اضافه شدند
