### ISSUE TITLE
کار اصلی این مرحله چیه؟

### ISSUE THREAD

**Issue by vahidalvandi** [parsisolution/gateway#28]
```
			$authorizedTransaction = $gateway->authorize($transaction);
			
			$refId =  $authorizedTransaction->getReferenceId(); // شماره ارجاع بانک
			$transID = $authorizedTransaction->getId(); // شماره تراکنش
			
```

چون بیشتر شبیه درگاهایی است که 2 مرحله ای پرداخت را انجام میدهند . 
وآیا روی همه درگاه ها کار میکند ؟

**Comment by vahidalvandi** [comment]
برای این قسمت هم خطای 
 new RequestTransaction
Class 'RequestTransaction' not found
میزنه

**Comment by hamed-ehtesham** [comment]
بله این کد روی همه ی درگاه ها کار میکنه. در مورد این که اسم شبیه به چی هست اگر فرصت دارید
#2 
رو مطالعه کنید بحث شده راجع بهش

در مورد
RequestTransaction
هم
ide
تون کلاس رو
import
نکرده حتما

```php
use Parsisolution\Gateway\Transactions\RequestTransaction;
```
