### ISSUE TITLE
مشکل ثبت اطلاعات بانک سامان

### ISSUE THREAD

**Issue by mostafaznv** [parsisolution/gateway#29]
با سلام.
من بانک سامان رو تست کردم و توی ثبت اطلاعات مشکل کوچیکی داره.

موقع دریافت اطلاعات توی کال‌بک، اطلاعات رو به درستی از بانک دریافت نمیکنه و همین باعث میشه که وریفای انجام نشه.
مشکل رو برطرف کردم و به زودی پول ریکوئست میدم.

اما یک مشکل دیگه وجود داره و اون هم اینه که بعد از وریفای کردن، باید رفرنس آی دی بانک  رو توی دیتابیس ذخیره کنیم (شما اون رو با مقدار آی دی تراکنش مقداردهی اولیه کردین) و متاسفانه من هیچ روشی رو نتونستم پیدا کنم که توی ساختار کد شما مقدار رفرنس آی دی رو آپدیت کنم.

میتونم یه اینستنس از دیتابیس بگیرم و آپدیت رو انجام بدم، اما دوست نداشتم یک کوئری به کوئری ها اضافه کنم و دوست داشتم توی ساختار فعلی بگنجه.

پیشنهادی دارید شما؟

**Comment by hamed-ehtesham** [comment]
اول تشکر بی نهایت به خاطر کارها و زحمت هایی که کشیدید
بله اتفاقا برای بانک پاسارگاد هم به این بحث خوردیم
قضیه این هست که شما به
api
.برای تغییر، دسترسی دارید اما معمولا نیاز نمیشه
برای ثبت
ref_id
میتونید از این روش استفاده کنید

```php
$this->transaction->updateReferenceId($referenceNumber);
```

برای نسخه ی یک فعلا اجازه بدید به این یک
query
بیشتر اشکال نگیریم من در نسخه ی 2 این رو حل میکنم که زمان
success
یا
fail
ref_id
هم در صورت نیاز
update
بشه و تعداد
query
کم بمونه
راستی نسخه ی 2 تغییرات خوبی داشته ولی هنوز روی نسخه ی 
alpha
هست خوشحال میشم اون هم استفاده کنید و تجربه تون رو در اختیارم قرار بدید و اگه پیشنهادی برای بهبودش دارید با کمال میل مشتاق شنیدنش هستم
نسخه ی 2 روی
dev branch
توسعه داده میشه

**Comment by mostafaznv** [comment]
مخلصم آقا.
فیکسش کردم و چندباری هم تست کردم.
به نظر میرسه که درست کار میکنه و دیتا رو هم به درستی توی دیتابیس میندازه.

در مورد ورژن دومت هم عالیه. شخصا از مدل توسعه لارابوک خیلی راضی نیستم. یکبار که نیاز شد تغییراتی توش بدم، متوجه شدم که تا دلت بخواد کوئری اضافه زده و خب مقداری با این موضوع مشکل دارم من :دی
 یا اینکه مثلا امکان پابلیش کردن مایگریشن ها رو داده، اما توی پکیجش هیچ فانکشنی وجود نداره که ستون اضافه باهاش ست کنی و خب این سوال پیش میاد که فرضا اگه من دیتابیس رو تغییر دادم، وقتی پکیج شما کلا براش مهم نیست، چه مزیتی داره این حرکت اصلا؟ :))
واسه شما دیدم که یه ستون جیسون داری که میشه باهاش یه کارایی کرد، اما اگه امکان هندل کردن ستون های مجزا رو هم اضافه کنی، قطعا به کار میاد.

در کل منتظر ورژن دوم شما هستم که برای پروژه های بعدیم از لارابوک به پکیج شما سوییچ کنم.

الان ۲۰ روزه که براشون پول ریکوئست زدم و کلا نیستن :)) البته بحثم پول ریکوئست خودم نیست، بحثم اون درصد زیادی از مردم هستن که دارن پکیج رو استفاده میکنن و پکیج مشکل داره و اینها هم براشون مهم نیست کلا

**Comment by hamed-ehtesham** [comment]
دست تون درد نکنه
یه اشکال کوچیک داشت که از 
dynamic property
استفاده کردید که از نظر برنامه نویسی خوب نیست
اگه از همون تابع
input 
استفاده بشه بهتر هست
باز هم تشکر بابت وقتی که گذاشتید
اگه وقت کردید تغییر بدید اون قسمت رو اگه نه خودم تغییر میدم

**Comment by mostafaznv** [comment]
متاسفانه با تابع اینپوت نال میگرفت.

**Comment by hamed-ehtesham** [comment]
عجیب هست

`
When using dynamic properties, Laravel will first look for the parameter's value in the request payload. If it is not present, Laravel will search for the field in the route parameters.
`

**Comment by mostafaznv** [comment]
نه آقا گویا من دیشب دیر موقع کار کردم و چشمام توی خواب بوده، الان تست کردم اوکیه :)))
حرفم هم به کلی منطقی نبود به همین دلیل دوباره تست کردم و دیدم اوکیه کار میکنه :))

الان تغییر میدم

**Comment by hamed-ehtesham** [comment]
خیلی ممنون

**Comment by mostafaznv** [comment]
اوکی شد آقا.

**Comment by hamed-ehtesham** [comment]
ممنون

بله حق با شماست حالا من سعی کردم
larabook
رو هم دنبال کنم اگه کسی سوالی مشکلی چیزی داشت راهنمایی ش کنم

**Comment by hamed-ehtesham** [comment]
نسخه ی 1.3.8 رو با تغییرات شما دادم بیرون

برای نسخه ی 2 که تعداد
query
ها بسیار کمتر شده جناب قاسم زاده
@alighasemzadeh
قرار بود چون ایشون درگاه های مختلف رو داشتن این نسخه رو تست کنن اما هنوز خبری ندادن که بریم روی این نسخه

**Comment by mostafaznv** [comment]
من فعلا فقط سامان رو دارم.
اگه نیاز بود بگین تست کنم.
