### ISSUE TITLE
ENUM is Evil!

### ISSUE THREAD

**Issue by erfansahaf** [parsisolution/gateway#31]
This is a gateway package that will get developed during the time and new providers will be added so why are you using ENUM datatype in your migration? 
You all owner of these gateway packages (Larabook, PasiSolution or Shirazsoft) are making the same mistake, ENUM is evil! Besides, it was created to get used for those fields which will not accept any new value ever!! If you are going to add new values (just like new providers name), the `port` field should not be ENUM, it should be INT or String (I prefer the INT one) so it can have new values.
The main reason that I don't use these gateway packages is their Migrations have a poor design.
If you want to read more about this, take a look at [this article](http://komlenic.com/244/8-reasons-why-mysqls-enum-data-type-is-evil/).

**Comment by hamed-ehtesham** [comment]
Hi Erfan,
thanks for your suggestion, i'm gonna change that in version 2 which is still on alpha phase,
and thanks for introducing that article, i read it

**Comment by aliqasemzadeh** [comment]
Hello,
Just change it to varchar.
