### ISSUE TITLE
کار نکردن activeDrivers

### ISSUE THREAD

**Issue by aliqasemzadeh** [parsisolution/gateway#32]
Non-static method Parsisolution\Gateway\GatewayManager::activeDrivers() should not be called statically (View: D:\programming\xampp\htdocs\ecommerce\resources\views\free-pay\index.blade.php)

سلام
در زمان ساخت 
activeDrivers
این خطا را می دهد.

**Comment by hamed-ehtesham** [comment]
با سلام
این تابع
static
نیست ولی شما به صورت
static
آن را فراخوانی کردید

**Comment by aliqasemzadeh** [comment]
سلام
این متود را دریک view می خواهم استفاده کنم

به نظرم این روش صحیح نیست باید 
static باشه

@hamed-ehtesham

**Comment by hamed-ehtesham** [comment]
با سلام
بله من هم فکر میکنم که
static
بودن کار راه انداز تر باشه برای این اما مشکل اینجا هست که من در حالت
static
دسترسی به محتویات فایل های
config
ندارم فعلا هم فرصت ندارم بررسی کنم که راهی هست یا نه ولی شما اگه میخواید
pull request
بفرستید بر ندارید یک چیز غلط رو تست نکرده یک
static
بهش اضافه کنید بفرستید یک کد درست بفرستید من هم قبول میکنم با کمال میل

**Comment by hamed-ehtesham** [comment]
من رفتم و نگاه کردم و دوباره یادآوری شد که شما اصلا اشتباه داشتید استفاده میکردید

اگه میخواید میتونید
static
هم استفاده کنید ولی شما کلاس اشتباهی رو انتخاب کرده بودید

```php
$activeDrivers = Gateway::activeDrivers();
```

نمونه کد همونطور که در #3 هم اشاره شده بود مثل بالاست در صورتی که شما میخواستید از کلاس
`GatewayManager`
استفاده کنید که اشتباه بوده

**Comment by aliqasemzadeh** [comment]
@hamed-ehtesham 
namespace Gateway
را بنویسید

**Comment by hamed-ehtesham** [comment]
سلام
facade
هست بنابرین
`Parsisolution\Gateway\Facades\Gateway`
همونطور که مینویسید

```php
Gateway::of('parsian')
```

همونطور مینویسید

```php
Gateway::activeDrivers();
```
