### ISSUE TITLE
درخواست و نحوه افزودن ماژول جدید سیزپی

### ISSUE THREAD

**Issue by vahidalvandi** [parsisolution/gateway#40]
سیزپی یک درگاه مستقیم است که بدون کارمزد کار میکند و دارای مجوز از بانک مرکزی است
[sizpay-Soap-PHP.zip](https://github.com/parsisolution/gateway/files/3622504/sizpay-Soap-PHP.zip)

نمونه درگاه  php

**Comment by hamed-ehtesham** [comment]
با سلام
به نسخه ی 1.4.0 اضافه شد

**Comment by vahidalvandi** [comment]
سلام . این ماژول چند تا مزیت دارد . ابتدا کارمزد ندارد و دوم تسویه روزانه
دارد و سوم امکان درج لوکو در صفحه پرداخت هم دارد.

ممنون از شما

**Comment by hamed-ehtesham** [comment]
لطفا در
callback
این کد رو قرار بدید

```php
$all = $request->all();

return compact('all');
```

و خروجی رو اینجا بفرستید
