### ISSUE TITLE
Target [Parsisolution\Gateway\Contracts\Factory] is not instantiable.

### ISSUE THREAD

**Issue by arbabi2010** [parsisolution/gateway#41]
سلام. ممنون بابت پکیجتون من برای درگاه پرداخت پارسیان چنین خطایی رو میگیرم 
Target [Parsisolution\Gateway\Contracts\Factory] is not instantiable.

**Comment by hamed-ehtesham** [comment]
با سلام
خطا واضح هست
شما نمیتونید از کلاس
Factory
نمونه سازی کنید
احتمالا از
`new`
استفاده کردید
اگه از نمونه کد استفاده کنید نباید مشکلی پیش بیاد
در صورتی که نیاز به راهنمایی بیشتری داشتید طریقه استفاده (تکه کد) رو به همراه بفرستید

**Comment by arbabi2010** [comment]
ممنون مشکل حل شد. توی داکیومنت نگفته بودین برای لاراول پایینتر از 5.5 پرووایدرش اضافه بشه . اضافه کردم اوکی شد.

**Comment by hamed-ehtesham** [comment]
حق با شماست
برای پایینتر از 5.5 تست نکرده بودم
