### ISSUE TITLE
ستون tracking_code چیست

### ISSUE THREAD

**Issue by vahidalvandi** [parsisolution/gateway#45]
مقدار این ستون توسط بانک پر میشود یا از طرف سایت ما ارسال میشود؟

**Comment by hamed-ehtesham** [comment]
از طرف بانک پر میشود برای پیگیری تراکنش

**Comment by vahidalvandi** [comment]
چون شبیه به مقدار id است

**Comment by hamed-ehtesham** [comment]
بسته به درگاه متفاوت است

یکسال پیش که من این کتابخونه رو نوشتم دیدی که الان نسبت به نحوه ی کارکرد درگاه ها دارم رو نداشتم انشاءالله تا چند ماه آینده نسخه ی دوم این کتابخونه رو میدم که این ابهامات رو هم تا حدی رفع میکنه
