### ISSUE TITLE
قابلیت دسترسی به ستونهای اضافه شده توسط کاربر

### ISSUE THREAD

**Issue by vahidalvandi** [parsisolution/gateway#46]
اضافه شدن یک ستون user_id
میتواند کاربردی باشد 
مخصوصا برای افرادی که لاگین هستند و خرید را انجام میدهند . ما میتوانیم خروجی تراکنش های یک کاربر را هم گزارش بگیرم

------

باید به شکلی باشد که در مرحله 
verify
بتوان یک آرایه را پاس داد و آن را روی جدول اصلی آپدیت کند

**Comment by hamed-ehtesham** [comment]
چون این مورد عمومی نیست میتونید خودتون قبل از انجام دادن
migration
اون رو اضافه کنید بعد
migrate
کنید

**Comment by vahidalvandi** [comment]
بهترین روش برای ارسال شماره کاربری به پکیج چطوره؟

**Comment by hamed-ehtesham** [comment]
شبیه به [این](https://github.com/parsisolution/gateway/issues/44#issuecomment-549236459) که
Person
رو فرستاده

**Comment by vahidalvandi** [comment]
توی توضیجات ؟ خودن میتونه روی ستون 
user_id
ثبتش کنه ؟

**Comment by hamed-ehtesham** [comment]
نه اون مثال که زدم توی ستون
extra
که از نوع
json
هست ذخیره میکنه فعلا کتابخونه قابلیت این رو نداره که در ستون های دیگه که تعریف نشدن چیزی ذخیره کنه ولی اگه فکر میکنید نیاز هست همچین موردی میشه به نسخه های بعد اضافه کرد این قابلیت رو

**Comment by vahidalvandi** [comment]
اره خیلی مهمه 
ما الان میخوایم گزارش بگیریم هر کاربر چه تراکنشی داشته  جدا از شماره فاکتوری که ما شماره تراکنش را قرار میدیم . میخوایم همه تراکنش های رخ داده یک کاربر را داشته باشیم

**Comment by vahidalvandi** [comment]
این موضوع در چند جای پروژه ممکن به کار میاد . 
مثلا یک ارایه را درهنگام 
verify
پاس بده که روی تراکنش آپدیت کند دقیقا همان لحظه ای که وضعیت فاکتور را به 
paid_at
ثبت میکند

**Comment by hamed-ehtesham** [comment]
نمونه در زمان ساخت درخواست پرداخت
```php
        $transaction = new RequestTransaction(new Amount(1400, 'IRT'));
        $transaction->setExtra([
            'mobile'      => '09123334444',
            'email'       => 'test@gmail.com',
            'description' => 'توضیحات تستی',
            'person'      => 12395,
        ]);
        $transaction['person_id'] = 225;
```
نمونه برای به روز رسانی در صورت موفق بودن تراکنش
```php
        $settledTransaction = Gateway::settle(true, ['person_id' => 333, 'invoice_id' => 5233]);
```
