### ISSUE TITLE
باگ در واحد پولی در payirr

### ISSUE THREAD

**Issue by vahidalvandi** [parsisolution/gateway#47]
سلام اگر به شکل زیر صدا زده شود به تومان تبدیل میشود
                    $transaction = new RequestTransaction(new Amount($request->total_amount,'IRR'));

اما اگر IRR برداشته شود اوکی است
                    $transaction = new RequestTransaction(new Amount($request->total_amount));

**Comment by vahidalvandi** [comment]
ضمن اینکه اکثر تراکنش ها برگشت میخورد

**Comment by hamed-ehtesham** [comment]
سلام
ممنون از اطلاع رسانی
pay.ir
api
ش رو عوض کرده بود که اعمال شد
نکته خوبش این هست که میشه از درگاه موبایلی هم استفاده کرد الان با ارسال شماره موبایل البته برای تراکنش های بالای 10 هزار تومن که از درگاه سامان استفاده میکنه (توی سایت خودشون در موردش توضیح دادن که چرا زیر 10 هزار تومن رو میفرستن ملت)


**نمونه کد برای استفاده از موبایل**

```php
        $transaction = new RequestTransaction(new Amount(50000, 'IRT'));
        $transaction->setExtra([
            'description' => 'توضیحات تستی',
            'person'      => 12395,
            'mobile'      => '09123334444'
        ]);
```

**Comment by vahidalvandi** [comment]
ممنون از شما
موبایلی همان سیستمی است که اطلاعات کارت در هنگام پرداخت بر اساس موبایل نمایش میده ؟

**Comment by hamed-ehtesham** [comment]
بله همون هست

**Comment by vahidalvandi** [comment]
در نسخه جدید شماره کارت را ذخیره نمیکند نسخه قبلی ذخیره میکرد

**Comment by vahidalvandi** [comment]
لطفا این مشکل را برطرف کنید آقای احتشامی
@hamed-ehtesham

**Comment by hamed-ehtesham** [comment]
مستندات که تغییری نشون نمیده من باز چک میکنم
