### ISSUE TITLE
پشنهاد اضافه کردن درگاه پرداخت با ارز دیجیتال

### ISSUE THREAD

**Issue by vahidalvandi** [parsisolution/gateway#48]
این درگاه جدید امکان پرداخت دلار و یا بیت کوین را از طریق ارز دیجیتال فراهم میکند
https://jeeb.io/docs
با توجه به تحریم پی پال بهترین جایگزین ارز دیجیتال است . درخواست ویژه دارم که حتما در اسرع وقت به ماژول های قابل پشتیبانی اضافه گردد

نمونه خارجی آن هم است که اگر بشه بهتره
https://bitpay.com/

این هم یک نمونه از پکیج لاراول برای نمونه خارجی
https://github.com/vrajroham/laravel-bitpay

**Comment by hamed-ehtesham** [comment]
با سلام
به نسخه‌ی ۲ درگاه‌هایی اضافه شدند که قابلیت پرداخت ارزی هم دارند از جمله [`یک‌پی`](https://yekpay.com) و [https://shepa.com](https://shepa.com) که میتوانید استفاده کنید درگاه ارزی یک‌پی الان روی یک پروژه واقعی که من خبر دارم در حال استفاده هست اما درگاه ارزی شپا رو اطلاع ندارم که استفاده شده یا خیر
در صورت نیاز به درگاه‌های دیگه میتونید به راحتی طبق آموزش اون‌ها رو در پروژه‌ی خودتون بدون تغییر در این package اضافه کنید
