### ISSUE TITLE
اضافه شدن درگاه واسط جدید

### ISSUE THREAD

**Issue by vahidalvandi** [parsisolution/gateway#49]
سلام پیشنهاد اضافه شدن درگاه 
payping 
را دارم

**Comment by hamed-ehtesham** [comment]
جناب الوندی سلام و وقت بخیر
اضافه کردن درگاه به این سیستم بسیار راحت هست شما اینکار رو انجام بدید و بعد
pull request
بفرستید حتما قبول میشه
من در حال حاضر درگیر چند پروژه هستم که باعث میشه داشتن وقت من برای فعالیتهای داوطلبانه و کمک به جامعه‌ی
Open Source
رو کاهش بده و نمیتونم قول بدم که تا چند وقت دیگه میرسم این کار رو انجام بدم ولی اگه شما یا دوستان دیگه اضافه کردنش رو انجام بدید و درخواست بفرستید برای قرار گرفتن در کد اصلی حتما سریع تر بررسی و اضافه میشه

**Comment by vahidalvandi** [comment]
من با معماری اشنا نیستم 
راهنمایی بفرمایید انجام میدیم

**Comment by vahidalvandi** [comment]
یک پیشنهاد دیگه داده بودم
https://github.com/parsisolution/gateway/issues/48
به نظرتون این میشه ؟

**Comment by hamed-ehtesham** [comment]
هر سه درگاهی که معرفی کردید میشه اضافه بشه

قبلا اینجا آموزش اضافه کردن داده شده:

https://github.com/parsisolution/gateway/issues/27#issuecomment-449749766

**Comment by vahidalvandi** [comment]
مهندس زحمت اینم بکش من تا سر از ساختارش در بیارم اخرش بی خیالش میشم
:)

**Comment by vahidalvandi** [comment]
ممنون آقای احتشام

**Comment by hamed-ehtesham** [comment]
خواهش میکنم

**Comment by vahidalvandi** [comment]
یک مشکلی که دارد وقتی واحد ریال ارسال میشود و واحد را هم ریال تعیین کرده ایم مجدد در ۱۰ ضرب میکند

`                    $transaction = new RequestTransaction(new Amount(10000 'IRR'));
`

و کلا مشکل دارد من مجبورم عدد را تقسیم بر ۱۰ کنم ولی در وریفای عدد ذخیره شده یک دهم اصلی است

**Comment by vahidalvandi** [comment]
لطفا این موضوع را سریع پیدا کنید خیلی فورسه . من یه خورده با کدهاش ور رفتم ولی نشد

**Comment by hamed-ehtesham** [comment]
سلام من درست خاطرم نیست ولی فکر میکنم این درگاه در مورد این که باید براش تومان ارسال شود یا ریال هیچ توضیحی نداده بود به خاطر همین احتمالا این اشکال پیش اومده نوع رو تغییر دادم نسخه‌ی جدید رو تست کنید

**Comment by vahidalvandi** [comment]
همچنین پیامی میده
{"amount":"Error converting value {null} to type 'System.Int32'. Path 'amount', line 1, position 26."}

**Comment by hamed-ehtesham** [comment]
چی پیام میده؟

**Comment by vahidalvandi** [comment]
{"amount":"Error converting value {null} to type 'System.Int32'. Path
'amount', line 1, position 26."}

**Comment by vahidalvandi** [comment]
آقای @hamed-ehtesham  لطفا بررسی بفرما
در هنگام برگشت به سایت جهت بررسی خطا داریم

**Comment by hamed-ehtesham** [comment]
لطفا در
callback
این کد رو قرار بدید

```php
$all = $request->all();

return compact('all');
```

و خروجی رو اینجا بفرستید

**Comment by vahidalvandi** [comment]
{"all":{"code":"396350","refid":"15007224526","clientrefid":"159324043523","cardnumber":"610433******8882","cardhashpan":"63AAA06A658BCAD863B0F4CFDAADFF71ECDC5FCD366A2F99149FA3279A3F7BD8","_token":"WVwAe58Ei3QbXd5LYmWRTE6iwbS8QhSWZQfsffgV","transaction_id":"159324043523"}}

**Comment by hamed-ehtesham** [comment]
مشکل از نمونه کد خود درگاه بوده ولی احتمالا باید مشکل حل شده باشه

**Comment by vahidalvandi** [comment]
ممنون تست میکنم

**Comment by vahidalvandi** [comment]
تایید نمیشه

"متافسانه سامانه قادر به دریافت کد پیگیری نمی‌باشد! نتیجه درخواست: 200"

**Comment by hamed-ehtesham** [comment]
https://github.com/payping/PHP-Basic-Example-Payment

نمونه کد خودشون رو تست کنید اگه نمونه کد خودشون کار نمیکنه اول مشکل رو با اون حل کنید بعد نمونه کدی که کار کنه رو بگید

**Comment by vahidalvandi** [comment]
من با این تکه کد قبلا در یه جای دیگه ای کار کردم

https://github.com/payping/payping-php-client#%D8%AA%D8%A7%DB%8C%DB%8C%D8%AF-%D9%BE%D8%B1%D8%AF%D8%A7%D8%AE%D8%AA

**Comment by hamed-ehtesham** [comment]
این که فرستادین نسخه‌ی قبل
api
هست و برای بیش از یک سال قبل اون که من فرستادم نسخه‌ی آخر
api
شون هست چک کنید اگه مشکلی داره اول با خود
payping
هماهنگ کنید که مشکل برطرف بشه بعد که نمونه کد درستی داشتید من میتونم کد رو درست کنم توی
document
شون هم توضیحات بیشتری نداشتن

**Comment by ashkanRmk** [comment]
> این که فرستادین نسخه‌ی قبل
> api
> هست و برای بیش از یک سال قبل اون که من فرستادم نسخه‌ی آخر
> api
> شون هست چک کنید اگه مشکلی داره اول با خود
> payping
> هماهنگ کنید که مشکل برطرف بشه بعد که نمونه کد درستی داشتید من میتونم کد رو درست کنم توی
> document
> شون هم توضیحات بیشتری نداشتن

از این داکیومنت استفاده کنین
https://help.payping.ir/fa/article/prdakht-sadh-drgah-prdakht-aintrnti-fkk25g/

**Comment by dolatkhah** [comment]
> همچنین پیامی میده
> {"amount":"Error converting value {null} to type 'System.Int32'. Path 'amount', line 1, position 26."}


> سلام من درست خاطرم نیست ولی فکر میکنم این درگاه در مورد این که باید براش تومان ارسال شود یا ریال هیچ توضیحی نداده بود به خاطر همین احتمالا این اشکال پیش اومده نوع رو تغییر دادم نسخه‌ی جدید رو تست کنید

مبلغ روی درگاه پی پینگ تومان هست

**Comment by dolatkhah** [comment]
> همچنین پیامی میده
> {"amount":"Error converting value {null} to type 'System.Int32'. Path 'amount', line 1, position 26."}

amount مبلغ پرداخت هست. 
مقدارش داره null به سرویس ارسال میشه. برای همین نمی تونه دیتا رو parse کنه.

**Comment by dolatkhah** [comment]
تو پیاده سازی سرویس پرداخت هر سوالی داشتید من در خدمتم. @vahidalvandi @hamed-ehtesham

**Comment by hamed-ehtesham** [comment]
فکر میکنم یه اشتباه تایپی برای حروف بزرگ و کوچیک رخ داده بود امیدوارم مشکل حل شده باشه
(امان از دست این زبان‌های مفسری)

**Comment by vahidalvandi** [comment]
حل شد
