### ISSUE TITLE
خطای جواب نام معتبر برای درگاه ملی

### ISSUE THREAD

**Issue by arbabi2010** [parsisolution/gateway#51]
سلام. وقتی از درگاه بانک ملی استفاده میکنم خطای جواب نامعتبر میده. خودم با استفاده از کدهایی که بانک داده بود تست کردم وارد درگاه میشد ولی با استفاده از این پکیج وقتی به قسمت authorize میرسه خطا میده. 
چطوری این خطا رو درست کنم؟

**Comment by hamed-ehtesham** [comment]
سلام
ببخشید بابت تاخیر در پاسخ
لطفا کدهایی که بانک داده رو ارسال کنید برام

**Comment by arbabi2010** [comment]
@hamed-ehtesham 
https://sadadpsp.ir/fa/content/310/%D9%86%D9%85%D9%88%D9%86%D9%87-%DA%A9%D8%AF%D9%87%D8%A7%DB%8C-php

**Comment by hamed-ehtesham** [comment]
سلام
من تغییرات رو طبق نمونه کد بانک که
api
ش رو تغییر داده بود اعمال کردم اما توی متن خطاها احتمال داره مشکل به وجود اومده باشه یا این که شماره کارت به درستی ذخیره نشه نکته‌ی دیگه این که فایل
config
هم کلیدهاش تغییر کرده حواستون باشه توی نسخه‌ی جدید که تغییرات رو اعمال کنید
اگه مشکلی بود اطلاع بدید که اصلاح بشه
