### ISSUE TITLE
بعد پرداخت

### ISSUE THREAD

**Issue by hosseinapex** [parsisolution/gateway#53]
بعد از پرداخت 
settledTransaction
به صورت null هستش 
و 
هنگام برگشت خطای 419 page expired 
میداد که مجبور شدم 
call backurl 
رو به exception 
ها اضافه کنم

**Comment by hamed-ehtesham** [comment]
با سلام
متاسفانه در نسخه‌های جدید laravel به دلیل مسائل امنیتی امکان post کردن از سایت‌های خارج از domain به عنوان مثال درگاه بانک در برگشت از درگاه و دریافت csrf token مورد استفاده‌ی laravel وجود ندارد مگر این که در قسمت `same_site` در فایل `config/session.php` مقدار را به `'none'` و یا `null` تغییر دهید که این مورد به خاطر تاثیر کلی روی برنامه‌ی شما و تضعیف امنیت سایت شما توصیه نمیشود بنابرین کاری که شما انجام دادید یعنی اضافه کردن مسیر callback به فایل `app/Http/Middleware/VerifyCsrfToken.php` توصیه میشود البته تنها اگر از درگاه‌هایی استفاده کنید که Callback رو به صورت post فراخوانی میکنند این مورد نیاز خواهد بود و برای درگاه‌هایی که Callback رو به صورت get فراخوانی میکنند این مورد نیاز نیست.
