### ISSUE TITLE
compatible with laravel 8

### ISSUE THREAD

**Issue by vahidalvandi** [parsisolution/gateway#56]
please compatible to laravel 8 very important

**Comment by vahidalvandi** [comment]
not work

**Comment by vahidalvandi** [comment]
سلام آقای احتشام اگر تست کنید پکیج در لاراول ۸ جدا از مساله نسخه کامپوزر در هنگام اتصال به درگاه صفحه سفید نمایش میدهد

**Comment by hamed-ehtesham** [comment]
با سلام
نسخه‌ی ۲ به خوبی روی نسخه‌های جدید laravel کار میکند
