### ISSUE TITLE
message: "View [redirector] not found."

### ISSUE THREAD

**Issue by arbabi2010** [parsisolution/gateway#60]
سلام .
من برای بانک پارسیان چنین خطایی رو دریافت میکنم
message: "View [redirector] not found."
علتش چیه ؟

**Comment by hamed-ehtesham** [comment]
با سلام
بعد از نصب package باید فایل‌های مورد نیازش رو publish کنید که همونطور که در readme گفته شده دستور زیر این کار رو انجام میده:

```bash
php artisan vendor:publish --provider="Parsisolution\Gateway\GatewayServiceProvider"
```
اگر مشکل همچنان وجود داشت force رو به دستور اضافه کنید به این شکل:

```bash
php artisan vendor:publish --force --provider="Parsisolution\Gateway\GatewayServiceProvider"
```
