### ISSUE TITLE
چرا پی پال حذف شده است؟

### ISSUE THREAD

**Issue by aliqasemzadeh** [parsisolution/gateway#9]
چرا پی پال حذف شده است؟

**Comment by hamed-ehtesham** [comment]
با سلام
paypal
فقط نمونه کد پیش فرض که خود
paypal
گذاشته بود رو گذاشته بودن و من مطمئن نبودم که کسی اون رو تست کرده و کار میکنه یا خیر و مورد مهم دیگه این که اون نمونه کد خطاها رو برنمیگردوند صرفا
return false
میکرد که درست نیست

**Comment by aliqasemzadeh** [comment]
@hamed-ehtesham
درگاه های ارزی باید وجود داشته باشند
حتی به نظرم یک پی باید اضافه بشخ

**Comment by hamed-ehtesham** [comment]
بله یک پی در برنامه هست که اضافه بشه و
[braintree](https://www.braintreepayments.com/)
